[package]
name = "profiling"
version = "0.1.0"
edition = "2021"


[dependencies]
ark-bn254 = "0.5"
poseidonito = { path = ".." }
flamegraph = "0.6"

[profile.profiling]
inherits = "release"
debug = true
lto = false
strip = false
