workspace = { members = ["profiling"] }

[package]
name = "poseidonito"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.5"   
ark-bn254 = "0.5"
hex = "0.4"
once_cell = "1.19"


[profile.profiling]
inherits = "release"
debug = true
lto = false
strip = false